void scenario1();
void scenario1Once(float *pElevTime, float *pAvgPasTime);
void scenario2Once(float *pElevTime, float *pAvgPasTime);
void scenario3Once(float *pElevTime, float *pAvgPasTime,int maxFloor1);
void scenario2();
void scenario3(int maxFloor1);
void findS3MaxFloor();
void findS4MaxFloor();
void scenario4(int maxFloor1,int maxFloor2);
void scenario4Once(float *pElevTime, float *pAvgPasTime,int maxFloor1,int maxFloor2);